FROM node:13-alpine

RUN apk add git g++ make python

# Create app directory
WORKDIR /usr/src/app

RUN npm i -g nodemon typescript @types/node eslint eslint-plugin-import ts-node


EXPOSE 9000

CMD ["nodemon"]
