version: "3.7"

# yaml refs
x-refs:
  common_config: &common_config
    logging:
      driver: gcplogs
      options:
        gcp-project: ${GCP_PROJECT}

services:
  postgres:
    <<: *common_config

  auth:
    <<: *common_config

  data:
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

  events:
    <<: *common_config

  actions:
    <<: *common_config
