FROM node:current-alpine

# Create app directory
WORKDIR /usr/src/app

RUN npm config set unsafe-perm true 
COPY package.json package-lock.json tsconfig.json .eslintrc.js ./
RUN npm i -g nodemon typescript @types/node eslint eslint-plugin-import ts-node
RUN npm i

EXPOSE 9000

CMD ["nodemon"]
